print("******")
print("*    *")
print("******")
print(          )
print("******")
print("******")
print("******")
print('         ')
# ARcha
print('   *')
print('  ***')
print(' *****')
print('*******')
print('   *  ')
print('   *  ')
# Yurak
print('              ')
print("  **   **  ")
print(" *  * *  * ")
print("*    *    *")
print(" *       * ")
print("  *     *  ")
print("   *   *   ")
print("    * *    ")
print("     *     ")

print('             ')
print("  ***     ***  ")
print(" *****   ***** ")
print("******* *******")
print(" ************* ")
print("  ***********  ")
print("   *********   ")
print("    *******    ")
print("     *****     ")
print("      ***      ")
print("       *       ")

# Tog`ri burchakli uchburchak`
print('         ')
print('  *')
print(' **')
print('***')

# AYlana
print('         ')
print(" * *")
print("*   *")
print(" * *")
# Doira
print('         ')
print(" * *")
print("* * *")
print(" * *")
print("         ")
print('        *        ')
print('        *        ')
print('        *        ')
print('        *        ')
print('*****************')
print('        *        ')
print('        *        ')
print('        *        ')
print('        *        ')
print("         ")

print('*****************')